/*
Generated by npm run actiontypes
Customized for reading board context
*/
import type { CommonEvent } from "./forge/events";
import type { RovoBoardContext } from "./jira/software/board";
export interface FetchActiveSprintDetailsPayload extends CommonEvent {
  boardId?: bigint;
  context: RovoBoardContext;
}
