/*
Generated by npm run actiontypes
Using ../scripts/actiontypes.ts
Payload interfaces are kept in sync with Actions & Inputs defined in manifest.yml
*/
import type { CommonEvent } from "./forge/events";
import type { RovoContext } from "./rovo/action";
// Need to override default RovoContext to grab board, if currently open in UI
import type { RovoBoardContext } from "./jira/software/board";
export interface FetchActiveSprintDetailPayload extends CommonEvent {
  boardId?: bigint;
  context: RovoBoardContext;
}
export interface RollSprintPayload extends CommonEvent {
  boardId?: bigint;
  context: RovoBoardContext;
}
